mainCat=Cookware
product=Pasta
cat=Speciality cookware

#product arguments should be passed to xpath by below parameters for region specific
productName=Chef frying pan
productDescription=Sleek lines, ergonomic handles and high quality materials
productPrice=€65,00
nameOfSelectOption =Option1-chef-braadpan

cartMsg=Your cart is currently empty

validSearchProduct="Frying pans"
invalidSearchProduct="airplane"
invalidSpecialCharacter="@@@###%%%"