mainCat=Cookware
product=Pasta
cat=Speciality cookware

#product arguments should be passed to xpath by below parameters for region specific
product_name=Chef frying pan
nameOfSelectOption =Option1-chef-braadpan