mainCat=Kookgerei
product=Pasta
cat=Gespecialiseerd keukengerei

productName=Chef braadpan
productDescription=Tijdloos & slim design: strakke lijnen,comfortabele grepen en hoogwaardig roestvrij staal

cartMsg=Uw winkelwagentje is momenteel leeg

validSearchProduct="braadpan"
invalidSearchProduct="airplane"
invalidSpecialCharacter="@@@###%%%"